name: oop
services:
  benchmarker:
#    image: localhost/benchmark-z3-15.0
    build:
      dockerfile: dynamic_solvers/Dockerfile
      context: ..
    environment:
      - CONFIG_CSV=/configs/runtime-variance.csv
      - OUTPUT_CSV=/out/results-${COMPOSE_PROJECT_NAME}.csv
      - VERBOSE=true
      - REAL_ENCODING=false
      - TRIALS=1
      # - BF=default
      # - ORDER=0,1,2,3
    # env_file: .env
    volumes:
      - ./configs:/configs
      - ./out:/out
